name: sen1522_2025
channels:
    - conda-forge/label/calliope_dev
    - conda-forge
    - gurobi
dependencies:
    - python=3.12
    - matplotlib
    - seaborn
    - plotly
    - jupyterlab
    - gurobi
    - calliope=0.7.0dev7
    - pyproj
    - pip
